
services:
  mkdocs:
    build: .
    container_name: mkdocs_live
    user: "appuser"
    ports:
      - "8000:8000"
    volumes:
      # Mount the current directory (.) to /app inside the container
      - .:/app