site_name: Study Sathi
repo_name: Vikramadtya/study-saathi
repo_url: https://github.com/Vikramadtya/study-saathi
edit_uri: edit/main/docs/ 

# A professional copyright notice for the footer
copyright: Copyright &copy; 2024 Vikramaditya Singh

theme:
  name: material
  
  features:
    - navigation.tabs 
    - navigation.tabs.sticky 
    - navigation.sections 
    - navigation.indexes # NEW: Allows folders to be clickable pages
    - navigation.top 
    - navigation.tracking 
    - search.suggest 
    - search.highlight 
    - content.code.copy 
    - content.code.annotate 
    - content.tabs.link 
    - content.tooltips

  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo 
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal 
      accent: cyan 
      toggle:
        icon: material/weather-sunny
        name: Switch to system preference

  font:
    text: Lora
    code: Atkinson Hyperlegible
    
  logo: assets/logo.svg
  favicon: assets/favicon.ico

plugins:
  - search
  - tags
  - glightbox
  - git-revision-date-localized
  - minify: # NEW: Compresses your site for faster loading
      minify_html: true
  - social: # ENHANCED: Generates beautiful sharing cards
      cards_layout_options:
        font_family: Lora
  - awesome-pages:
      collapse_single_pages: true 

markdown_extensions:
  - toc:
      permalink: true 
  - admonition 
  - attr_list
  - md_in_html
  - abbr
  - def_list
  - footnotes
  - pymdownx.details 
  - pymdownx.blocks.caption
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.tilde
  - pymdownx.mark 
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences:
      custom_fences: 
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true 
  - pymdownx.arithmatex:
      generic: true

extra:
  generator: false
  social:
    - icon: fontawesome/solid/person
      link: https://www.vikramaditya-singh.in
    - icon: fontawesome/solid/blog
      link: https://www.neuralcook.com/home
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/vikrmadityasngh/

extra_javascript:
  - javascripts/mathjax.js # NEW: The required glue code for MathJax
  - https://polyfill.io/v3/polyfill.min.js?features=es6 # NEW: Polyfill for older browsers
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js